package projecteuler.p001to009;

import java.util.ArrayList;

public class P2EvenFibonacciNumbers {
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.	
 */
	public static void main(String[] args) 
	{
		int MAX = 4000000;
		
		int lastNumber = 1, newNumber = 1, sum = 0;
		ArrayList<Integer> intArray = new ArrayList<Integer>();
		
		while(newNumber < MAX)
		{
			int tempNumber = newNumber;

			if(newNumber % 2 == 0)
			{
				intArray.add(newNumber);
			 	sum += newNumber;
			}
			
			newNumber = newNumber + lastNumber;
			lastNumber = tempNumber;
		}
		
		System.out.println(intArray);
		System.out.println("Sum: " + sum);
	}
}
